openapi: 3.2.0
info:
  title: Roku Nabu Cloud Healthz API
  contact:
    name: DevX Tools Team
    email: dldevxtools@roku.com
  version: 1.3.29
  description: Nabu Cloud is Roku's developer cloud platform for managing test devices, snapshots, builds, projects, organisations, groups, and personal access tokens. It provides REST APIs for orchestrating remote Roku test devices and CI/CD workflows.
  x-generated-from: rokudev/dev-doc
  x-source-url: https://github.com/rokudev/dev-doc/blob/v2.0/reference/openapi.json
servers:
- url: https://api.cloud.roku.dev
  description: Roku Nabu Cloud Production
tags:
- name: healthz
paths:
  /api/v1/-/livez:
    get:
      tags:
      - healthz
      summary: Roku Healthz
      operationId: healthz-healthz
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Healthz-Healthz
  /api/v1/-/readyz:
    get:
      tags:
      - healthz
      summary: Roku Readyz
      operationId: healthz-readyz
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Healthz-Readyz
